### ISSUE TITLE
Type error when uploading eigen value

### ISSUE THREAD

**Issue by jishnu94** [sophianetSun/fingerprint-reader#3]
```
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    main()
  File "main.py", line 20, in main
    show_input_command()
  File "main.py", line 37, in show_input_command
    print(fpr.up_comp_many([49, 0, 196, 0, 0]))
  File "/home/pi/fingerprint-reader/fingerprint.py", line 411, in up_comp_many
    res = self.send_cmd_packet(header, packet, 8)
  File "/home/pi/fingerprint-reader/fingerprint.py", line 132, in send_cmd_packet
    assert (Command(header[0]) == Command.HEAD and
TypeError: Command() takes no arguments
```

**Comment by RobbyGit** [comment]
I know thi sis old but did you ever solve this .. I am pulling my hair out with the little documentation

**Comment by RobbyGit** [comment]
Yeah this looks strange... Dont know if this should have been there as its always going to throw an assert. Pity
